/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* A Preemptive Round-Robin Task Scheduler */

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

TCB_t user_tasks[MAX_TASKS];
uint32_t g_tick_cnt = 0;
uint32_t current_task = 1;

int main(void)
{

	EnableProcessorFaults();

	SchedStack_Init(SCHED_START_STACK);

	Init_TaskStack();

	Init_LEDs();

	Init_SystickTimer(TICK_HZ);

	change_sp_to_psp();

	Task1_Handler();

    /* Loop forever */
	for(;;);
}


__attribute__((naked)) void IdleTask_Handler(void)
{
	while (1)
	{
		__asm volatile("WFI");
	}
}

void Task1_Handler(void)
{
	while (1)
	{
		toggle_led(LED_1);
		task_delay(1000);
	}
}

void Task2_Handler(void)
{
	while (1)
	{
		toggle_led(LED_2);
		task_delay(500);
	}
}

void Task3_Handler(void)
{
	while (1)
	{
		toggle_led(LED_3);
		task_delay(250);
	}
}
